default:
  base_output_path: ./output
  spatial_resolution: 0.04167 # resolution in degree units
  covariables:
    path: ./data/worldclim2_bio
    is_worldclim: true
    variables:
      - bio_1
      - bio_2
      - bio_3
      - bio_4
      - bio_5
      - bio_6
      - bio_7
      - bio_8
      - bio_9
      - bio_10
      - bio_11
      - bio_12
      - bio_13
      - bio_14
      - bio_15
      - bio_16
      - bio_17
      - bio_18
      - bio_19
  regional:
    use_regional_cutoff: true
    shapefile_region_path: ./data/ecoregions/Ecoregions2017_America.shp
  future_projection_config:
    aoi: ./data/aoi/norteamerica.shp
    rasters:
      - ./data/future_worldclim/wc2.1_2.5m_bioc_BCC-CSM2-MR_ssp370_2021-2040.tif
      - ./data/future_worldclim/wc2.1_2.5m_bioc_BCC-CSM2-MR_ssp245_2021-2040.tif
